id: A22078DD2
base_file: f3D06.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:16:54.150365
  last_modified_at: 2022-05-31 05:16:54.150372
