id: A22078DD2
base_file: fFAAA.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:16:54.156706
  last_modified_at: 2022-05-31 05:16:54.156709
