id: A22078DD2
base_file: f3938.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:16:54.095553
  last_modified_at: 2022-05-31 05:16:54.095562
